### PR TITLE
Optimization patch for pager

### PR DESCRIPTION
**Pull request by Tsuser1**
General optimizations have been implemented. Added comments.

### CODE REVIEW

**Comment by J4D3N** [comment]
Why do you subtract one when the page index is 1 (current page is 1)?

`index = (ranks.size() < 9) ? 0 : (index != 1) ? ((index - 1) * 8 + 1) : ((index - 1) * 8);`

**Comment by Tsuser1** [comment]
Its a weird issue, trust me on that one. Has to do with how multiplication acts if its only one page.

**Comment by J4D3N** [comment]
The only problems I have with the code are:
- Conventions must be followed, brackets, additions brackets, try and catch statements.
- You are creating unnecessary array objects of Rank when you could convert the collection to a single array.

E.g. `Rank[] ranks = rankManager.getRanks().toArray(new Rank[0]);`

**Comment by J4D3N** [comment]
You can see that every time it outputs a line for the rank page, you create an object array of Rank type. This could be spammed and actually cause much more garbage collection than needed.

**Pull request merged**
